version: '3.7'
services:
  hadoop-master:
    image: prass016/hadoop_spark_master
    container_name: hadoop-master
    hostname: hadoop-master
    ports: 
      - "2222:2222"
      - "4040:4040"
      - "8020:8020"
      - "8088:8088"
      - "9001:9001"
      - "50070:50070"
      - "50090:50090"
    expose:
      - "8030-8050"
    networks:
      spark:
        aliases:
          - hadoop-master
          - hadoop-slave-1
          - hadoop-slave-2

  hadoop-slave-1:
    image: prass016/hadoop_spark_slave
    container_name: hadoop-slave-1
    hostname: hadoop-slave-1
    ports:
      - "8042:8042"
      - "50075:50075"
    expose:
      - "34000-48000"
      - "50010"
      - "50020"
      - "50040"
    depends_on:
      - hadoop-master
    networks:
      spark:
        aliases:
          - hadoop-master
          - hadoop-slave-1
          - hadoop-slave-2

  hadoop-slave-1:
    image: prass016/hadoop_spark_slave
    container_name: hadoop-slave-1
    hostname: hadoop-slave-1
    ports:
      - "8042:8042"
      - "50075:50075"
    expose:
      - "34000-48000"
      - "50010"
      - "50020"
      - "50040"
    depends_on:
      - hadoop-master
    networks:
      spark:
        aliases:
          - hadoop-master
          - hadoop-slave-1
          - hadoop-slave-2


networks:
  spark:
    driver: bridge
